path:
  - permissions
plugin: add
actions:
  'create action content':
    value: 'create action content'
  'delete action revisions':
    value: 'delete action revisions'
  'delete any action content':
    value: 'delete any action content'
  'edit any action content':
    value: 'edit any action content'
  'revert action revisions':
    value: 'revert action revisions'
  'view action revisions':
    value: 'view action revisions'
